#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# [Git Bash issues with CLI tools · Issue #390 · Schniz/fnm](https://github.com/Schniz/fnm/issues/390#issuecomment-776240883)
eval $(fnm env | sed 1d)
export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH

if [[ -f .node-version || -f .nvmrc ]]; then
    fnm use
fi

fnm use default
rm -rf pnpm-lock.yaml
pnpm install
pnpm format