name: 'Automated Testing'

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '43 11 * * 2'
  
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests
      uses: microsoft/playwright-github-action@v1.5.4
  
